spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://YOUR-MYSQL-ENDPOINT:3306/your_db
    username: your_user
    password: your_password